# Generated by Django 3.2.5 on 2021-08-13 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_rename_slug_category_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='slug',
        ),
    ]
